version: '3.8'
services:
  # This service starts the datajoint database image
  db:
    # image: datajoint/mysql:5.6
    # image: datajoint/mysql:5.7
    image: datajoint/mysql:8.0
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      ## persist data across docker-compose up/down
      - ./data:/var/lib/mysql
      ## modify MySQL config
      # - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10